services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"

  adminer:
    image: adminer
    restart: always
#    ports:
#      - 8080:8080
    export:
      - 8080

